name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=latest
        docker build -t my-python-app .
        docker tag my-python-app:latest <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-python-app:$IMAGE_TAG
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/my-python-app:$IMAGE_TAG

    - name: Deploy with Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
