name: Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::261219435789:role/github-actions-role
        aws-region: eu-west-2

    - name: Verify AWS Caller Identity
      run: aws sts get-caller-identity

    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 261219435789.dkr.ecr.eu-west-2.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=latest
        docker build -t my-python-app .
        docker tag my-python-app:latest 261219435789.dkr.ecr.eu-west-2.amazonaws.com/my-python-app:$IMAGE_TAG
        docker push 261219435789.dkr.ecr.eu-west-2.amazonaws.com/my-python-app:$IMAGE_TAG

    - name: Deploy ECS Service
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
