name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to read repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::261219435789:role/github-actions-role
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: eu-west-2

    - name: Verify AWS Caller Identity
      run: aws sts get-caller-identity

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Deployment Package
      run: zip -r deploy.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        application_name: MyPythonApp
        environment_name: MyPythonApp-env
        version_label: v-${{ github.run_number }}
        region: eu-west-2
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

